### ISSUE TITLE
Convert project to maven aggregator project

### ISSUE THREAD

**Issue by alex-zuy** [sevntu-checkstyle/methods-distance#14]
Currently project consists of two separate maven sub-projects where *methods-distance-web* subproject depends on *methods-distance* by declaring plain maven artifact dependency which is resolved through local repository.
This approach has several drawbacks:
- It means that whenever we build *web* subproject we must make shure that we already installed the latest build of *methods-distance* subproject to maven local repo.
- To build entire project we need to issue something like following command:
```
mvn -f methods-distance/pom.xml install && mvn -f methods-distance-web/pom.xml install
```
- CI build and deployment scripts gets more complicated

I suggest converting project to [maven aggregator project](https://maven.apache.org/pom.html#Aggregation) to make build simpler.

**Comment by romani** [comment]
Right
