### ISSUE TITLE
Constructors group division penalty

### ISSUE THREAD

**Issue by romani** [sevntu-checkstyle/methods-distance#27]
consider real case - https://github.com/checkstyle/checkstyle/pull/3438#issuecomment-250331108

Constructors should not be divided, it is good to have them together.

**Comment by alex-zuy** [comment]
Current implementation treats constructors as overloaded methods and adds penalty if they are split. Should we treat grouping of constructors separately to allow using separate penalty function coefficient for such cases? I think this might make sense as IMHO splitting constructors is less acceptable than splitting methods.

**Comment by romani** [comment]
yes, please make special coefficient.
