### ISSUE TITLE
create wiki pages with links to google docs files 

### ISSUE THREAD

**Issue by romani** [sevntu-checkstyle/methods-distance#3]
we did few documents about optimization process in google docs
please put links to them from wiki pages of github repo. No need to translate them to English.

**Comment by alex-zuy** [comment]
please, [review](https://github.com/sevntu-checkstyle/methods-distance/wiki/Methods-ordering-investigation)

**Comment by romani** [comment]
@alex-zuy ,

1) please review all referenced documents and remove our conversation-comments .
2) please create a document to have general ideas of distance optimization, all other documents will be examples of manual optimization process.
3) does it make sense to translate them to English ? to be ready continued by anybody in web.

**Comment by alex-zuy** [comment]
@romani , please review [this document](https://docs.google.com/document/d/1RqJK35imO7rB_MITtIL-kbL2MqhZl6X25ngxmjcTCzM/edit?usp=sharing) for point 2.

**Comment by romani** [comment]
Looks good, content is small so please put it to wiki page , examples could stay in ggogledocs format.

**Comment by alex-zuy** [comment]
@romani , fixed. Please, review [this wiki page](https://github.com/sevntu-checkstyle/methods-distance/wiki/Distance-optimization).

**Comment by romani** [comment]
make link from https://github.com/sevntu-checkstyle/methods-distance/wiki/Methods-ordering-investigation and close the issue.

**Comment by alex-zuy** [comment]
Added link to "Distance optimization" page
