### ISSUE TITLE
Analysis misses some dependencies

### ISSUE THREAD

**Issue by wilcoln** [sevntu-checkstyle/methods-distance#55]
This problem was discovered in conversation for PR https://github.com/checkstyle/checkstyle/pull/7960, which is about optimizing the methods distance in `checkstyle.api.FileText` class.

A quick look at that class shows us that `public int size()` is used in `findLineBreaks()`,
but for some reason analysis does not capture that dependency.

To visualize this yourself, checkout the provided [dsm report](https://wilcoln.github.io/com.pupppycrawl.tools.checkstyle.api/after.FileText.java.html).

**Comment by romani** [comment]
PR to fix problem is welcome.

**Comment by romani** [comment]
Fix is merged
